# Generated by Django 5.1.2 on 2025-01-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='coursecode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
