# Generated by Django 5.1.2 on 2025-02-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0003_alter_students_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='coursecode',
            field=models.CharField(max_length=100),
        ),
    ]
