# Generated by Django 5.1.2 on 2025-02-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0004_alter_students_coursecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
